apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.4-alpine
        args: ["--requirepass", "$(REDIS_PWD)"]
        env:
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis-pwd
              key: REDIS_PWD
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 5Mi
          limits:
            cpu: 200m
            memory: 100Mi
      volumes:
      - name: redis-pwd
        secret:
          secretName: redis-pwd
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
